GET http://localhost:3000 HTTP/1.1

###

GET http://localhost:3000/books HTTP/1.1

###
#With optional parameters and pagination

GET http://localhost:3000/books?keyword=&page= ' HTTP/1.1

###

GET http://localhost:3000/books/656c81ca0bbb4028e8cb85e6

###

POST http://localhost:3000/books/new  HTTP/1.1
content-type: application/json

{
    "title" : "Book 1",
    "description" : "Book 1 description",
    "author" : "Author 1",
    "price" : 100,
    "category" : "Adventure"
}

###

PUT http://localhost:3000/books/656e10f838460c7e6a057bcd  HTTP/1.1
content-type: application/json

{
    "title" : "Book 3",
    "description" : "Book 3 description",
    "author" : "Author 3",
    "price" : 100,
    "category" : "Fantasy"
}

###

DELETE  http://localhost:3000/books/656c89df717a51bf784660b8