GET http://localhost:3000 HTTP/1.1

###

GET http://localhost:3000/books HTTP/1.1

###

GET http://localhost:3000/comments?parentId=655a3ecd3f9161299d2c53d2

###

POST http://localhost:3000/books/new  HTTP/1.1
content-type: application/json

{
    "title" : "Book 1",
    "description" : "Book 1 description",
    "author" : "Author 1",
    "price" : 100,
    "category" : "Adventure"
}